# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a=np.random.rand(2,3,5)
a

array([[[1.90260392e-01, 9.47044759e-01, 8.77383646e-01, 6.93313893e-02,
         9.20309163e-01],
        [2.60617967e-01, 6.77042868e-01, 5.93834979e-01, 5.70989747e-04,
         4.38778942e-01],
        [8.39178721e-01, 6.93707708e-01, 9.49533539e-01, 1.42109316e-01,
         3.72528083e-01]],

       [[1.03968922e-01, 9.06957762e-01, 2.62490352e-01, 1.06905973e-03,
         8.73968059e-01],
        [6.81909311e-01, 2.60397545e-01, 9.84265036e-02, 5.11472813e-01,
         8.37759516e-01],
        [5.59610548e-01, 6.27822402e-01, 7.36398411e-01, 6.86518135e-01,
         5.81716085e-01]]])

In [5]:
a = np.random.randint(0, 100, size=(2, 3, 5))
a

array([[[81, 80, 38, 98, 39],
        [58,  4,  1, 32, 87],
        [77, 59, 95, 84, 74]],

       [[11, 36, 68, 17,  9],
        [ 6, 19, 16, 68, 64],
        [81, 83, 83, 35, 97]]])

In [6]:
a = np.random.random((2,3,5))
a

array([[[0.67820476, 0.62454173, 0.59332344, 0.71480567, 0.26294794],
        [0.472581  , 0.54967209, 0.569886  , 0.92558456, 0.94093357],
        [0.97560896, 0.02835993, 0.40385355, 0.27931594, 0.42659607]],

       [[0.70126878, 0.97350416, 0.03581946, 0.89795456, 0.19467288],
        [0.25551716, 0.50072684, 0.26135586, 0.09893908, 0.40153815],
        [0.40126112, 0.32224129, 0.90923795, 0.17432234, 0.15492786]]])

In [7]:
print(a)


[[[0.67820476 0.62454173 0.59332344 0.71480567 0.26294794]
  [0.472581   0.54967209 0.569886   0.92558456 0.94093357]
  [0.97560896 0.02835993 0.40385355 0.27931594 0.42659607]]

 [[0.70126878 0.97350416 0.03581946 0.89795456 0.19467288]
  [0.25551716 0.50072684 0.26135586 0.09893908 0.40153815]
  [0.40126112 0.32224129 0.90923795 0.17432234 0.15492786]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [9]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
a == b


/var/folders/_3/p7g0czqs2mn2vrf8z2svm6ph0000gn/T/ipykernel_78308/3817457479.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == b


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
np.add(a,b)
#no they are not the same array shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c=np.transpose(b, axes=(1,2,0)) 
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
d=(np.add(a,c))
print(d)

[[[1.67820476 1.62454173 1.59332344 1.71480567 1.26294794]
  [1.472581   1.54967209 1.569886   1.92558456 1.94093357]
  [1.97560896 1.02835993 1.40385355 1.27931594 1.42659607]]

 [[1.70126878 1.97350416 1.03581946 1.89795456 1.19467288]
  [1.25551716 1.50072684 1.26135586 1.09893908 1.40153815]
  [1.40126112 1.32224129 1.90923795 1.17432234 1.15492786]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print(a ),(d)

[[[0.67820476 0.62454173 0.59332344 0.71480567 0.26294794]
  [0.472581   0.54967209 0.569886   0.92558456 0.94093357]
  [0.97560896 0.02835993 0.40385355 0.27931594 0.42659607]]

 [[0.70126878 0.97350416 0.03581946 0.89795456 0.19467288]
  [0.25551716 0.50072684 0.26135586 0.09893908 0.40153815]
  [0.40126112 0.32224129 0.90923795 0.17432234 0.15492786]]]


(None,
 array([[[1.67820476, 1.62454173, 1.59332344, 1.71480567, 1.26294794],
         [1.472581  , 1.54967209, 1.569886  , 1.92558456, 1.94093357],
         [1.97560896, 1.02835993, 1.40385355, 1.27931594, 1.42659607]],
 
        [[1.70126878, 1.97350416, 1.03581946, 1.89795456, 1.19467288],
         [1.25551716, 1.50072684, 1.26135586, 1.09893908, 1.40153815],
         [1.40126112, 1.32224129, 1.90923795, 1.17432234, 1.15492786]]]))

In [ ]:
#Both have same array shape but different elements

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e=print(np.multiply(a, c))

[[[0.67820476 0.62454173 0.59332344 0.71480567 0.26294794]
  [0.472581   0.54967209 0.569886   0.92558456 0.94093357]
  [0.97560896 0.02835993 0.40385355 0.27931594 0.42659607]]

 [[0.70126878 0.97350416 0.03581946 0.89795456 0.19467288]
  [0.25551716 0.50072684 0.26135586 0.09893908 0.40153815]
  [0.40126112 0.32224129 0.90923795 0.17432234 0.15492786]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
a == e

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
d_max=(np.max(d))
print(d_max)

1.9756089627033222


In [18]:
d_min=(np.min(d))
print(d_min)

1.0283599296723227


In [19]:
d_mean=(np.mean(d))
print(d_mean)

1.4909834233917623


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [20]:
f=np.empty([2,3,5])
print(f)

[[[0.67820476 0.62454173 0.59332344 0.71480567 0.26294794]
  [0.472581   0.54967209 0.569886   0.92558456 0.94093357]
  [0.97560896 0.02835993 0.40385355 0.27931594 0.42659607]]

 [[0.70126878 0.97350416 0.03581946 0.89795456 0.19467288]
  [0.25551716 0.50072684 0.26135586 0.09893908 0.40153815]
  [0.40126112 0.32224129 0.90923795 0.17432234 0.15492786]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [21]:
f = np.array((d))
f

array([[[1.67820476, 1.62454173, 1.59332344, 1.71480567, 1.26294794],
        [1.472581  , 1.54967209, 1.569886  , 1.92558456, 1.94093357],
        [1.97560896, 1.02835993, 1.40385355, 1.27931594, 1.42659607]],

       [[1.70126878, 1.97350416, 1.03581946, 1.89795456, 1.19467288],
        [1.25551716, 1.50072684, 1.26135586, 1.09893908, 1.40153815],
        [1.40126112, 1.32224129, 1.90923795, 1.17432234, 1.15492786]]])

In [22]:
a=np.where((f>d_min)&(f<d_mean),25,f)
b=np.where((f>d_mean)&(f<d_max),75,a)
c=np.where((f==d_mean),50,b)
d=np.where((f==d_min),0,c)
e=np.where((f==d_max),100,d)
print(e)

[[[ 75.  75.  75.  75.  25.]
  [ 25.  75.  75.  75.  75.]
  [100.   0.  25.  25.  25.]]

 [[ 75.  75.  25.  75.  25.]
  [ 25.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [23]:
print(d)

[[[75.         75.         75.         75.         25.        ]
  [25.         75.         75.         75.         75.        ]
  [ 1.97560896  0.         25.         25.         25.        ]]

 [[75.         75.         25.         75.         25.        ]
  [25.         75.         25.         25.         25.        ]
  [25.         25.         75.         25.         25.        ]]]


In [24]:
print(f)

[[[1.67820476 1.62454173 1.59332344 1.71480567 1.26294794]
  [1.472581   1.54967209 1.569886   1.92558456 1.94093357]
  [1.97560896 1.02835993 1.40385355 1.27931594 1.42659607]]

 [[1.70126878 1.97350416 1.03581946 1.89795456 1.19467288]
  [1.25551716 1.50072684 1.26135586 1.09893908 1.40153815]
  [1.40126112 1.32224129 1.90923795 1.17432234 1.15492786]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [25]:
i=np.where((d>d_min)&(d<d_mean),"A",d)
j=np.where((d>d_mean)&(d<d_max),"B",i)
k=np.where((d==d_mean),"C",j)
l=np.where((d==d_min),"D",k)
m=np.where((d==d_max),"E",l)
print(m)

[[['75.0' '75.0' '75.0' '75.0' '25.0']
  ['25.0' '75.0' '75.0' '75.0' '75.0']
  ['E' '0.0' '25.0' '25.0' '25.0']]

 [['75.0' '75.0' '25.0' '75.0' '25.0']
  ['25.0' '75.0' '25.0' '25.0' '25.0']
  ['25.0' '25.0' '75.0' '25.0' '25.0']]]
