# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [8]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [16]:
a=np.random.rand(2,3,5)
a

array([[[0.24190667, 0.75955575, 0.3292977 , 0.94163319, 0.29571079],
        [0.13007818, 0.52370777, 0.25657834, 0.54663664, 0.08013631],
        [0.32836443, 0.08041808, 0.59753564, 0.65466965, 0.88051953]],

       [[0.58603485, 0.76157539, 0.35235376, 0.36789517, 0.56640426],
        [0.57292665, 0.64016409, 0.80430251, 0.17681441, 0.11255465],
        [0.62585848, 0.22354957, 0.75587679, 0.01294285, 0.34903562]]])

In [21]:
a = np.random.randint(0, 100, size=(2, 3, 5))
a

array([[[33, 11, 22, 11, 18],
        [32, 80, 39, 30, 71],
        [59, 59, 40, 81, 65]],

       [[78, 96, 78, 60, 59],
        [ 1, 14, 65, 83, 65],
        [55, 59, 25, 60, 43]]])

In [25]:
a = np.random.random((2,3,5))
a

array([[[0.60293429, 0.78551218, 0.37312277, 0.07710868, 0.54223359],
        [0.01245373, 0.77347761, 0.11365214, 0.8425106 , 0.29194555],
        [0.32273034, 0.0945195 , 0.94125747, 0.00913683, 0.64190205]],

       [[0.69181473, 0.72158623, 0.93939055, 0.49660187, 0.69518841],
        [0.55353876, 0.4777358 , 0.12911811, 0.77407004, 0.82911929],
        [0.26148219, 0.90767561, 0.12063084, 0.4644141 , 0.87285183]]])

In [41]:
print(a)


[[[0.92027593 0.53381106 0.17538126 0.91527712 0.70480289]
  [0.68592027 0.04834665 0.4245738  0.09255937 0.72600719]
  [0.88669128 0.71319839 0.29355647 0.57914885 0.46589869]]

 [[0.049326   0.1729704  0.89030106 0.666498   0.65608354]
  [0.90870705 0.67266539 0.75728069 0.49745867 0.08868383]
  [0.71369462 0.78239153 0.4274078  0.28875367 0.56282178]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [39]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [40]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [43]:
a == b


/var/folders/_3/p7g0czqs2mn2vrf8z2svm6ph0000gn/T/ipykernel_97449/3817457479.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == b


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [ ]:
# your code here

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
# your code/answer here

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code/answer here

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here